{1}{1}25.000000
{0}{82}Det kommer et romskip.
{88}{362}Jenny er ei jente. Samir er en gutt. De er venner. De har en hage.
{364}{927}- Sukkererter er godt, sa Jenny. - Vi kan så frø, så får vi mange. - Kræsj! Brak! Brekk! Knus! Noe stort landet i treet. Det var ei kule. Var den av glass? Var den farlig?
{932}{1447}Noe falt ut. En person hang i ei grein. - En rar person, sa Jenny lavt. - Den har lange ører som en rev! - En rar katt, sa Samir stille. - Den har sko!
{1448}{1825}Personen hoppet ned. Katta hoppet ned. Personen la handa over hjertet sitt og sa: - Ikke vær redde. Vi kommer i fred.  
{1828}{2223}- Jeg heter Hen. Dette er Katt. Vi har reist langt.  Vi har reist forbi Neptun, Uranus, Saturn,  Jupiter og Mars.
{2224}{2643}- Hvor kommer dere fra? spurte Samir. - Fra planeten Mo-lo. Vi har vann. Vi kan snakke og forstå alle språk. Sola vår heter Proxima Centauri.
{2644}{3114}- Den kula der er vel ikke sterk, sa Samir. - Jo, sa Hen.  - Den er laget av gzi-gzy fra et fjell.  Gzi-gzy betyr mu-lig på deres språk. Vi har reist med mu-lig.
{3115}{3402}- Ta på disse brillene, sa Hen. - De er laget av fjellet gzi-gzy.  Jenny tok på seg brillene.  Samir tok på seg brillene.
{3403}{3660}- Jeg ser et stort dyr! ropte Samir. Det er gult og brunt og har pels! En bjørn som kan fly!
{3661}{4092}- Nå bader den i en stor blomst! Blomsten drysser gult støv på den! - Støvet er pollen, sa Hen. - Det kommer fra hannblomster. Eller gutter, hvis du skjønner det bedre.
{4093}{4456}- Nå sitter den på en gul blomst på treet her! sa Jenny og pekte. Det er hundre gule stilker med kuler på. - Kulene har pollen, sa Hen.
{4457}{4847}- Mellom stilkene er det små grønne krukker, sa Jenny. – Bjørnen har snabel. Nå suger den vann fra de grønne kulene. - Det er sukker-vann, sa Hen. – Nektar. Mat.
{4848}{5405}- Bjørn med snabel og vinger, lo Samir. - Er det en elefantbjørn? - Blomsten rister gult støv på dyret, sa Jenny. - Dyret klør seg, så Samir. – Den børster seg! - Hen sa: Dyret har kurver på beina. Det samler blomsterstøv. Mat.
{5406}{5587}Dyret fløy til treet som sto ved stiden av. Der var det grønne blomster. Mange små.
{5588}{5955}Mellom blomstene var det små grønne krukker med saft. Dyret sugde saft med snabelen sin. - Hunnblomster, sa Hen. - Eller jenter, om du skjønner det bedre. Mye saft.
{5956}{6421}Jenny så på dyret. Det gule støvet på pelsen ble klint av på de grønne blomstene. Hen sa: -Blomsterstøv fra hannblomst til hunn-blomst. Pollinering. Blir frø. 
{6422}{6699}Dyret fløy vekk. - Nektar i magen og pollen i kurver, sa Hen. - Mat for dyret. Mat for dem som skal bli nye dyr.
{6700}{7189}Jenny og Samir tok av seg brillene. - Hva var det vi så, sa Samir. - Der er det, smilte Hen og pekte. De så bare ei humle. - He? Vanlig humle og vanlig seljeblomst?
{7190}{7696}- Vanlig? sa Hen. - Hva er vanlig? Ikke noe å bry seg om, tenker du? Men hvis du ser, virkelig ser, da skjer det merkelige ting. Kanskje du kan se det, uten disse brillene? 
{7697}{8334}Katt sa ingenting. Katt skrudde på skruer og hjul i beltet sitt. Jenny spurte: Men hvorfor kom dere hit?  Hen smilte og sa: - Dere får vite det. Siden. Vær tålmodig. Tiden er din venn.
